name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker images
      - name: Build Docker Images
        run: |
          docker compose build

      # Start containers
      - name: Start Containers
        run: |
          docker compose up -d

      # Wait for services to be healthy
      - name: Wait for Services
        run: |
          echo "Waiting for services to be ready..."
          sleep 10 # Adjust the sleep time as needed for your services to start

      # Perform a basic health check using curl
      - name: Perform Curl Check
        run: |
          curl -fsSL http://localhost:3000 || exit 1

      - name: Clean up Containers
        run: |
            echo "Stopping and removing containers..."
            docker compose down


      
